/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  authorName?: string;
  authorDetail?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  published?: boolean;
  sortOrder?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Staff = {
  _id: string;
  _type: "staff";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: string;
  sortOrder?: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  startAt?: string;
  location?: string;
  summary?: string;
  body?: BlockContent;
  linkUrl?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type DownloadableResource = {
  _id: string;
  _type: "downloadableResource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: "ero" | "policy" | "enrolment" | "newsletter" | "general";
  publishedAt?: string;
  description?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  featured?: boolean;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  primaryNavigation?: Array<
    {
      _key: string;
    } & NavPrimaryItem
  >;
  footerLinks?: Array<
    {
      _key: string;
    } & LinkItem
  >;
  footerTagline?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  schoolName?: string;
  tagline?: string;
  intro?: string;
  homeStats?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
  principalMessage?: string;
  principalPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  homeHeroEyebrow?: string;
  homeHeroTitle?: string;
  homeHeroSubtitle?: string;
  homeCtas?: Array<
    {
      _key: string;
    } & LinkItem
  >;
  homeHighlightSlides?: Array<
    {
      _key: string;
    } & HomeHighlightSlide
  >;
  homeHeroBackground?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  innerPageHeroes?: Array<
    {
      _key: string;
    } & InnerPageHero
  >;
  specialCharacterSummary?: string;
  contactAddress?: string;
  contactEmail?: string;
  contactPhone?: string;
  officeHours?: string;
  facebookUrl?: string;
  heroAppUrl?: string;
  absenceUrl?: string;
  newsletterUrl?: string;
  policiesUrl?: string;
  alertEnabled?: boolean;
  alertSeverity?: "info" | "warning" | "critical";
  alertTitle?: string;
  alertMessage?: string;
  alertLinkLabel?: string;
  alertLinkUrl?: string;
  alertStart?: string;
  alertEnd?: string;
  defaultSeoDescription?: string;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  siteUrl?: string;
};

export type NavPrimaryItem = {
  _type: "navPrimaryItem";
  variant?: "simple" | "group";
  link?: LinkItem;
  groupLabel?: string;
  landingLink?: LinkItem;
  children?: Array<
    {
      _key: string;
    } & LinkItem
  >;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type NewsPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "newsPost";
};

export type LinkItem = {
  _type: "linkItem";
  label?: string;
  linkDestination?: "siteRoute" | "cmsPage" | "newsPost" | "file" | "external";
  siteRoute?:
    | "/"
    | "/about"
    | "/learning"
    | "/community"
    | "/enrolment"
    | "/news"
    | "/resources"
    | "/contact";
  page?: PageReference;
  newsPost?: NewsPostReference;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  href?: string;
  openInNewTab?: boolean;
};

export type NewsPost = {
  _id: string;
  _type: "newsPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  excerpt?: string;
  body?: BlockContent;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type InnerPageHero = {
  _type: "innerPageHero";
  pageKey?:
    | "about"
    | "learning"
    | "community"
    | "contact"
    | "enrolment"
    | "resources"
    | "news";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type HomeHighlightSlide = {
  _type: "homeHighlightSlide";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  published?: boolean;
  link?: LinkItem;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | Staff
  | Event
  | BlockContent
  | Slug
  | SanityFileAssetReference
  | DownloadableResource
  | Navigation
  | SiteSettings
  | NavPrimaryItem
  | PageReference
  | NewsPostReference
  | LinkItem
  | NewsPost
  | Page
  | InnerPageHero
  | HomeHighlightSlide
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    _id,    _updatedAt,    schoolName,    tagline,    intro,    homeStats[]{_key, label, value},    principalMessage,    principalPhoto,    homeHeroEyebrow,    homeHeroTitle,    homeHeroSubtitle,    homeCtas[]{  label,  linkDestination,  linkType,  siteRoute,  href,  openInNewTab,  "pageSlug": page->slug.current,  "newsSlug": newsPost->slug.current,  "fileUrl": file.asset->url},    homeHighlightSlides[]{_key, title, description, published, image, link{  label,  linkDestination,  linkType,  siteRoute,  href,  openInNewTab,  "pageSlug": page->slug.current,  "newsSlug": newsPost->slug.current,  "fileUrl": file.asset->url}},    homeHeroBackground,    innerPageHeroes[]{ pageKey, image },    specialCharacterSummary,    contactAddress,    contactEmail,    contactPhone,    officeHours,    facebookUrl,    heroAppUrl,    absenceUrl,    newsletterUrl,    policiesUrl,    alertEnabled,    alertSeverity,    alertTitle,    alertMessage,    alertLinkLabel,    alertLinkUrl,    alertStart,    alertEnd,    defaultSeoDescription,    defaultOgImage,    siteUrl  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  _updatedAt: string;
  schoolName: string | null;
  tagline: string | null;
  intro: string | null;
  homeStats: Array<{
    _key: string;
    label: string | null;
    value: string | null;
  }> | null;
  principalMessage: string | null;
  principalPhoto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  homeHeroEyebrow: string | null;
  homeHeroTitle: string | null;
  homeHeroSubtitle: string | null;
  homeCtas: Array<{
    label: string | null;
    linkDestination:
      | "cmsPage"
      | "external"
      | "file"
      | "newsPost"
      | "siteRoute"
      | null;
    linkType: null;
    siteRoute:
      | "/"
      | "/about"
      | "/community"
      | "/contact"
      | "/enrolment"
      | "/learning"
      | "/news"
      | "/resources"
      | null;
    href: string | null;
    openInNewTab: boolean | null;
    pageSlug: string | null;
    newsSlug: string | null;
    fileUrl: string | null;
  }> | null;
  homeHighlightSlides: Array<{
    _key: string;
    title: string | null;
    description: string | null;
    published: boolean | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    link: {
      label: string | null;
      linkDestination:
        | "cmsPage"
        | "external"
        | "file"
        | "newsPost"
        | "siteRoute"
        | null;
      linkType: null;
      siteRoute:
        | "/"
        | "/about"
        | "/community"
        | "/contact"
        | "/enrolment"
        | "/learning"
        | "/news"
        | "/resources"
        | null;
      href: string | null;
      openInNewTab: boolean | null;
      pageSlug: string | null;
      newsSlug: string | null;
      fileUrl: string | null;
    } | null;
  }> | null;
  homeHeroBackground: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  innerPageHeroes: Array<{
    pageKey:
      | "about"
      | "community"
      | "contact"
      | "enrolment"
      | "learning"
      | "news"
      | "resources"
      | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }> | null;
  specialCharacterSummary: string | null;
  contactAddress: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  officeHours: string | null;
  facebookUrl: string | null;
  heroAppUrl: string | null;
  absenceUrl: string | null;
  newsletterUrl: string | null;
  policiesUrl: string | null;
  alertEnabled: boolean | null;
  alertSeverity: "critical" | "info" | "warning" | null;
  alertTitle: string | null;
  alertMessage: string | null;
  alertLinkLabel: string | null;
  alertLinkUrl: string | null;
  alertStart: string | null;
  alertEnd: string | null;
  defaultSeoDescription: string | null;
  defaultOgImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  siteUrl: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation" && _id == "navigation"][0]{    primaryNavigation[]{      _key,      variant,      link{  label,  linkDestination,  linkType,  siteRoute,  href,  openInNewTab,  "pageSlug": page->slug.current,  "newsSlug": newsPost->slug.current,  "fileUrl": file.asset->url},      groupLabel,      landingLink{  label,  linkDestination,  linkType,  siteRoute,  href,  openInNewTab,  "pageSlug": page->slug.current,  "newsSlug": newsPost->slug.current,  "fileUrl": file.asset->url},      children[]{  label,  linkDestination,  linkType,  siteRoute,  href,  openInNewTab,  "pageSlug": page->slug.current,  "newsSlug": newsPost->slug.current,  "fileUrl": file.asset->url}    },    footerLinks[]{  label,  linkDestination,  linkType,  siteRoute,  href,  openInNewTab,  "pageSlug": page->slug.current,  "newsSlug": newsPost->slug.current,  "fileUrl": file.asset->url},    footerTagline  }
export type NAVIGATION_QUERY_RESULT = {
  primaryNavigation: Array<{
    _key: string;
    variant: "group" | "simple" | null;
    link: {
      label: string | null;
      linkDestination:
        | "cmsPage"
        | "external"
        | "file"
        | "newsPost"
        | "siteRoute"
        | null;
      linkType: null;
      siteRoute:
        | "/"
        | "/about"
        | "/community"
        | "/contact"
        | "/enrolment"
        | "/learning"
        | "/news"
        | "/resources"
        | null;
      href: string | null;
      openInNewTab: boolean | null;
      pageSlug: string | null;
      newsSlug: string | null;
      fileUrl: string | null;
    } | null;
    groupLabel: string | null;
    landingLink: {
      label: string | null;
      linkDestination:
        | "cmsPage"
        | "external"
        | "file"
        | "newsPost"
        | "siteRoute"
        | null;
      linkType: null;
      siteRoute:
        | "/"
        | "/about"
        | "/community"
        | "/contact"
        | "/enrolment"
        | "/learning"
        | "/news"
        | "/resources"
        | null;
      href: string | null;
      openInNewTab: boolean | null;
      pageSlug: string | null;
      newsSlug: string | null;
      fileUrl: string | null;
    } | null;
    children: Array<{
      label: string | null;
      linkDestination:
        | "cmsPage"
        | "external"
        | "file"
        | "newsPost"
        | "siteRoute"
        | null;
      linkType: null;
      siteRoute:
        | "/"
        | "/about"
        | "/community"
        | "/contact"
        | "/enrolment"
        | "/learning"
        | "/news"
        | "/resources"
        | null;
      href: string | null;
      openInNewTab: boolean | null;
      pageSlug: string | null;
      newsSlug: string | null;
      fileUrl: string | null;
    }> | null;
  }> | null;
  footerLinks: Array<{
    label: string | null;
    linkDestination:
      | "cmsPage"
      | "external"
      | "file"
      | "newsPost"
      | "siteRoute"
      | null;
    linkType: null;
    siteRoute:
      | "/"
      | "/about"
      | "/community"
      | "/contact"
      | "/enrolment"
      | "/learning"
      | "/news"
      | "/resources"
      | null;
    href: string | null;
    openInNewTab: boolean | null;
    pageSlug: string | null;
    newsSlug: string | null;
    fileUrl: string | null;
  }> | null;
  footerTagline: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)].slug.current
export type PAGE_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/lib/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    _updatedAt,    title,    slug,    excerpt,    heroImage,    body,    seoTitle,    seoDescription,    ogImage  }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: BlockContent | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: NEWS_POSTS_LIST_QUERY
// Query: *[_type == "newsPost"] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    publishedAt,    excerpt,    heroImage  }
export type NEWS_POSTS_LIST_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: NEWS_POST_SLUGS_QUERY
// Query: *[_type == "newsPost" && defined(slug.current)].slug.current
export type NEWS_POST_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/lib/queries.ts
// Variable: NEWS_POST_BY_SLUG_QUERY
// Query: *[_type == "newsPost" && slug.current == $slug][0]{    _id,    _updatedAt,    title,    slug,    publishedAt,    excerpt,    heroImage,    body,    seoTitle,    seoDescription,    ogImage  }
export type NEWS_POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: BlockContent | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_NEWS_QUERY
// Query: *[_type == "newsPost"] | order(publishedAt desc)[0...3]{    _id,    title,    "slug": slug.current,    publishedAt,    excerpt  }
export type HOME_NEWS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: UPCOMING_EVENTS_QUERY
// Query: *[_type == "event" && startAt >= now()] | order(startAt asc)[0...3]{    _id,    title,    "slug": slug.current,    startAt,    location,    summary,    linkUrl  }
export type UPCOMING_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  startAt: string | null;
  location: string | null;
  summary: string | null;
  linkUrl: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: EVENT_SLUGS_QUERY
// Query: *[_type == "event" && defined(slug.current)].slug.current
export type EVENT_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/lib/queries.ts
// Variable: EVENT_BY_SLUG_QUERY
// Query: *[_type == "event" && slug.current == $slug][0]{    _id,    _updatedAt,    title,    "slug": slug.current,    startAt,    location,    summary,    body,    linkUrl  }
export type EVENT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  startAt: string | null;
  location: string | null;
  summary: string | null;
  body: BlockContent | null;
  linkUrl: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && published == true] | order(sortOrder asc, _createdAt desc)[0...3]{    _id,    quote,    authorName,    authorDetail,    photo,    sortOrder  }
export type HOME_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string | null;
  authorName: string | null;
  authorDetail: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  sortOrder: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: DOWNLOADABLE_RESOURCES_QUERY
// Query: *[_type == "downloadableResource"] | order(featured desc, publishedAt desc) {    _id,    title,    category,    publishedAt,    description,    featured,    "fileUrl": file.asset->url,    "fileName": file.asset->originalFilename  }
export type DOWNLOADABLE_RESOURCES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  category: "enrolment" | "ero" | "general" | "newsletter" | "policy" | null;
  publishedAt: string | null;
  description: string | null;
  featured: boolean | null;
  fileUrl: string | null;
  fileName: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: STAFF_MEMBERS_QUERY
// Query: *[_type == "staff"] | order(sortOrder asc, name asc)[0...12]{    _id,    name,    role,    bio,    photo  }
export type STAFF_MEMBERS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  bio: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    _id,\n    _updatedAt,\n    schoolName,\n    tagline,\n    intro,\n    homeStats[]{_key, label, value},\n    principalMessage,\n    principalPhoto,\n    homeHeroEyebrow,\n    homeHeroTitle,\n    homeHeroSubtitle,\n    homeCtas[]{\n  label,\n  linkDestination,\n  linkType,\n  siteRoute,\n  href,\n  openInNewTab,\n  "pageSlug": page->slug.current,\n  "newsSlug": newsPost->slug.current,\n  "fileUrl": file.asset->url\n},\n    homeHighlightSlides[]{_key, title, description, published, image, link{\n  label,\n  linkDestination,\n  linkType,\n  siteRoute,\n  href,\n  openInNewTab,\n  "pageSlug": page->slug.current,\n  "newsSlug": newsPost->slug.current,\n  "fileUrl": file.asset->url\n}},\n    homeHeroBackground,\n    innerPageHeroes[]{ pageKey, image },\n    specialCharacterSummary,\n    contactAddress,\n    contactEmail,\n    contactPhone,\n    officeHours,\n    facebookUrl,\n    heroAppUrl,\n    absenceUrl,\n    newsletterUrl,\n    policiesUrl,\n    alertEnabled,\n    alertSeverity,\n    alertTitle,\n    alertMessage,\n    alertLinkLabel,\n    alertLinkUrl,\n    alertStart,\n    alertEnd,\n    defaultSeoDescription,\n    defaultOgImage,\n    siteUrl\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "navigation" && _id == "navigation"][0]{\n    primaryNavigation[]{\n      _key,\n      variant,\n      link{\n  label,\n  linkDestination,\n  linkType,\n  siteRoute,\n  href,\n  openInNewTab,\n  "pageSlug": page->slug.current,\n  "newsSlug": newsPost->slug.current,\n  "fileUrl": file.asset->url\n},\n      groupLabel,\n      landingLink{\n  label,\n  linkDestination,\n  linkType,\n  siteRoute,\n  href,\n  openInNewTab,\n  "pageSlug": page->slug.current,\n  "newsSlug": newsPost->slug.current,\n  "fileUrl": file.asset->url\n},\n      children[]{\n  label,\n  linkDestination,\n  linkType,\n  siteRoute,\n  href,\n  openInNewTab,\n  "pageSlug": page->slug.current,\n  "newsSlug": newsPost->slug.current,\n  "fileUrl": file.asset->url\n}\n    },\n    footerLinks[]{\n  label,\n  linkDestination,\n  linkType,\n  siteRoute,\n  href,\n  openInNewTab,\n  "pageSlug": page->slug.current,\n  "newsSlug": newsPost->slug.current,\n  "fileUrl": file.asset->url\n},\n    footerTagline\n  }\n': NAVIGATION_QUERY_RESULT;
    '\n  *[_type == "page" && defined(slug.current)].slug.current\n': PAGE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    title,\n    slug,\n    excerpt,\n    heroImage,\n    body,\n    seoTitle,\n    seoDescription,\n    ogImage\n  }\n': PAGE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "newsPost"] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    excerpt,\n    heroImage\n  }\n': NEWS_POSTS_LIST_QUERY_RESULT;
    '\n  *[_type == "newsPost" && defined(slug.current)].slug.current\n': NEWS_POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "newsPost" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    title,\n    slug,\n    publishedAt,\n    excerpt,\n    heroImage,\n    body,\n    seoTitle,\n    seoDescription,\n    ogImage\n  }\n': NEWS_POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "newsPost"] | order(publishedAt desc)[0...3]{\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    excerpt\n  }\n': HOME_NEWS_QUERY_RESULT;
    '\n  *[_type == "event" && startAt >= now()] | order(startAt asc)[0...3]{\n    _id,\n    title,\n    "slug": slug.current,\n    startAt,\n    location,\n    summary,\n    linkUrl\n  }\n': UPCOMING_EVENTS_QUERY_RESULT;
    '\n  *[_type == "event" && defined(slug.current)].slug.current\n': EVENT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "event" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    startAt,\n    location,\n    summary,\n    body,\n    linkUrl\n  }\n': EVENT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "testimonial" && published == true] | order(sortOrder asc, _createdAt desc)[0...3]{\n    _id,\n    quote,\n    authorName,\n    authorDetail,\n    photo,\n    sortOrder\n  }\n': HOME_TESTIMONIALS_QUERY_RESULT;
    '\n  *[_type == "downloadableResource"] | order(featured desc, publishedAt desc) {\n    _id,\n    title,\n    category,\n    publishedAt,\n    description,\n    featured,\n    "fileUrl": file.asset->url,\n    "fileName": file.asset->originalFilename\n  }\n': DOWNLOADABLE_RESOURCES_QUERY_RESULT;
    '\n  *[_type == "staff"] | order(sortOrder asc, name asc)[0...12]{\n    _id,\n    name,\n    role,\n    bio,\n    photo\n  }\n': STAFF_MEMBERS_QUERY_RESULT;
  }
}
